version: '3.3'

services:
  backend:
    build:
      context: ./Backend-Neos/neos-spring-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./web-blume
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      API_PATH: http://backend:8080  
    depends_on:
      - backend
