name: Update Project Full from Backend

on:
  push:
    branches:
      - dev

jobs:
  update_project_full:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend
        uses: actions/checkout@v2

      - name: Trigger update on project-full
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.TOKEN_SPTECH }}" \
          https://api.github.com/repos/SPTech-Neos/scripts/dispatches \
          -d '{"event_type":"backend_update"}'