name: Update from Backend and Frontend

on:
  repository_dispatch:
    types: [backend_update, frontend_update]

jobs:
  update_from_backend_and_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto-full
        uses: actions/checkout@v2

      - name: Check if backend folder exists
        run: |
          if [ -d "backend" ]; then
            cd backend
            git checkout dev
            git pull origin dev
            cd ..
          fi

      - name: Check if frontend folder exists
        run: |
          if [ -d "frontend" ]; then
            cd frontend
            git checkout test
            git pull origin test
            cd ..
          fi

      - name: Check if user email is configured
        run: |
          if ! git config --global --get user.email; then
            git config --global user.email "victor.liracarlos@gmail.com"
            git config --global user.name "VicLira"
          fi

      - name: Add, Commit and Push Changes
        run: |
          git add .
          git commit -m "Update from backend and frontend"
          git push